### ISSUE TITLE
Traceback while running ansible-test sanity through importer

### ISSUE THREAD

**Issue by anshulbehl** [ansible/galaxy_ng#127] opened 2020-04-28 21:29 UTC
##### SUMMARY

PE team is seeing exception traces while importer runs sanity suite on a collection in Automation Hub.

##### STEPS TO REPRODUCE

Please check the [link](https://cloud.redhat.com/ansible/automation-hub/my-imports?namespace=ibm&name=spectrum_virtualize&version=1.0.3)

You would need access to the `ibm` namespace to check the logs.

This is causing a lot of sanity tests to not run at all and PE team cannot judge if the collection is passing sanity tests if there is no local run involved

##### EXPECTED RESULTS

Exceptions should be handled and all sanity tests should run.

##### ACTUAL RESULTS

Seeing exceptions

```
Running sanity test 'no-dict-itervalues' with Python 3.6 
Running sanity test 'no-get-exception' with Python 3.6 
Running sanity test 'no-illegal-filenames' with Python 3.6 
Running sanity test 'no-main-display' with Python 3.6 
Running sanity test 'no-smart-quotes' with Python 3.6 
Running sanity test 'no-unicode-literals' with Python 3.6 
Running sanity test 'pep8' with Python 3.6 
Running sanity test 'pylint' with Python 3.6 
ERROR: Command "/usr/bin/python3.6 -m pylint --jobs 0 --reports n --max-line-length 160 --rcfile /usr/local/lib/python3.6/dist-packages/ansible_test/_data/sanity/pylint/config/collection.cfg --output-format json --load-plugins deprecated,blacklist,string_format tests/unit/plugins/module_utils/test_ibm_svc_utils.py tests/unit/plugins/modules/test_ibm_svc_host.py tests/unit/plugins/modules/test_ibm_svc_info.py tests/unit/plugins/modules/test_ibm_svc_mdisk.py tests/unit/plugins/modules/test_ibm_svc_mdiskgrp.py tests/unit/plugins/modules/test_ibm_svc_vdisk.py tests/unit/plugins/modules/test_ibm_svc_vol_map.py" returned exit status 1. 
>>> Standard Error 
Process ChildLinter-2: 
Traceback (most recent call last): 
File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap 
self.run() 
File "/usr/local/lib/python3.6/dist-packages/pylint/lint.py", line 241, in run 
for file_or_module in iter(tasks_queue.get, "STOP"): 
File "<string>", line 2, in get 
File "/usr/lib/python3.6/multiprocessing/managers.py", line 757, in _callmethod 
kind, result = conn.recv() 
File "/usr/lib/python3.6/multiprocessing/connection.py", line 250, in recv 
buf = self._recv_bytes() 
File "/usr/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes 
buf = self._recv(4) 
File "/usr/lib/python3.6/multiprocessing/connection.py", line 383, in _recv 
raise EOFError 
EOFError 
Process ChildLinter-3: 
Traceback (most recent call last): 
File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap 
```

**Comment by anshulbehl** [comment] 2020-04-28 21:29
cc: @awcrosby

**Comment by awcrosby** [comment] 2020-04-29 00:05
Closing as this is a duplicate of #64

**Closed by awcrosby** 2020-04-29 00:05 UTC
Labels: area/importer, priority/high, status/in-progress, type/bug
