### ISSUE TITLE
UI: Imports from UI to use inbound-[namespace] url

### ISSUE THREAD

**Issue by awcrosby** [ansible/galaxy_ng#368] opened 2020-08-06 17:45 UTC
Imports started from the UI should stop posting to the `automation-hub` url and repo, and instead use the `inbound-[namespace]` url and repo.

Related to #20

**Comment by newswangerd** [comment] 2020-08-06 20:55
@awcrosby I believe this is already done

https://github.com/ansible/ansible-hub-ui/pull/163

Can you test it?

**Comment by chouseknecht** [comment] 2020-08-10 15:06
Duplicate of #290

**Closed by chouseknecht** 2020-08-10 15:06 UTC
Labels: area/frontend, priority/high, status/new, type/enhancement
