### ISSUE TITLE
Please don't render files in module-utils directory for collections

### ISSUE THREAD

**Issue by abenokraitis** [ansible/galaxy_ng#260] opened 2020-06-22 15:15 UTC
### Use Case
Users don't need to see files in module-utils in what's rendered in any collection view

### Proposed Solution
Just remove them. No need to crawl that directory, they are treated like libraries.

### Alternatives
Re-label and hide, and make explicit to view

### Implementation
1. Remove entirely
2. Leave but do not show as plugins, nor make them on the same "level" as modules and plugins directly called by users

**Comment by abenokraitis** [comment] 2020-06-22 15:16
CC: @ikhan2010

**Comment by chouseknecht** [comment] 2020-10-12 15:57
Duplicate of #299

**Closed by chouseknecht** 2020-10-12 15:57 UTC
Labels: area/importer, priority/low, status/new, type/enhancement
