### ISSUE TITLE
Apparently valid module documentation complains of syntax error

### ISSUE THREAD

**Issue by Qalthos** [ansible/galaxy_ng#301] opened 2020-07-13 21:20 UTC
##### SUMMARY

Module documentation that renders on docs.ansible.com shows "Documentation Syntax Error: cannot parse plugin documention."

##### STEPS TO REPRODUCE

Not sure yet. Some modules render just fine. The JSON shown appears to validate and I don't see anything obviously wrong with it.

##### EXPECTED RESULTS

Something along the lines of http://docs.testing.ansible.com/ansible/2.10/collections/arista/eos/eos_acl_interfaces_module.html#ansible-collections-arista-eos-eos-acl-interfaces-module

##### ACTUAL RESULTS

https://cloud.redhat.com/ansible/automation-hub/arista/eos/content/module/eos_acl_interfaces

**Comment by chouseknecht** [comment] 2020-09-22 15:02
Duplicate of #377

**Closed by chouseknecht** 2020-09-22 15:02 UTC
Labels: area/importer, priority/medium, status/new, type/bug
