### ISSUE TITLE
UI: Fix buggy namespace card

### ISSUE THREAD

**Issue by newswangerd** [ansible/galaxy_ng#228] opened 2020-06-09 14:14 UTC
In some environments the namespace card it showing up like this: 
![Screen Shot 2020-06-09 at 10 12 27 AM](https://user-images.githubusercontent.com/6063371/84158444-e0d2f180-aa39-11ea-9203-ae42ce002ca0.png)

**Comment by chouseknecht** [comment] 2020-09-22 15:04
Cannot reproduce. We think it was fixed by an update to Patternfly.

**Closed by chouseknecht** 2020-09-22 15:04 UTC
Labels: area/frontend, priority/high, status/new, type/bug
