### ISSUE TITLE
Pod terminated while uploading a collection to AH

### ISSUE THREAD

**Issue by anshulbehl** [ansible/galaxy_ng#146] opened 2020-05-05 18:27 UTC
##### SUMMARY

Pod terminated while uploading a collection to AH
Raised by F5 while uploading their collection.
##### STEPS TO REPRODUCE

Try to upload the tarball present here, 
https://galaxy.ansible.com/download/f5networks-f5_modules-1.3.0.tar.gz

##### EXPECTED RESULTS

Collection should upload successfully and importer should also run fine
##### ACTUAL RESULTS

```
'terminated'
  File "/venv/lib64/python3.6/site-packages/rq/worker.py", line 884, in perform_job
    rv = job.perform()
  File "/venv/lib64/python3.6/site-packages/rq/job.py", line 664, in perform
    self._result = self._execute()
  File "/venv/lib64/python3.6/site-packages/rq/job.py", line 670, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/venv/lib64/python3.6/site-packages/pulp_ansible/app/tasks/collections.py", line 131, in import_collection
    artifact_file, filename=filename, logger=import_logger
  File "/venv/lib64/python3.6/site-packages/galaxy_importer/collection.py", line 53, in import_collection
    return _import_collection(file, filename, logger, cfg)
  File "/venv/lib64/python3.6/site-packages/galaxy_importer/collection.py", line 68, in _import_collection
    file=file, logger=logger).run()
  File "/venv/lib64/python3.6/site-packages/galaxy_importer/ansible_test/runners/openshift_job.py", line 77, in run
    job.cleanup()
  File "/venv/lib64/python3.6/site-packages/galaxy_importer/ansible_test/runners/openshift_job.py", line 321, in cleanup
    reason = pod['status']['containerStatuses'][0]['state']['terminated']['reason']
```

**Comment by anshulbehl** [comment] 2020-05-05 18:38
cc: @awcrosby

**Comment by awcrosby** [comment] 2020-05-06 13:12
Closing as this is a duplicate of https://github.com/ansible/galaxy_ng/issues/130

**Closed by awcrosby** 2020-05-06 13:12 UTC
