### ISSUE TITLE
Unable to publish vyos.vyos collection due to 'terminate' error

### ISSUE THREAD

**Issue by pabelanger** [ansible/galaxy_ng#259] opened 2020-06-22 14:08 UTC
## Bug Report
we seem to have an issue release 1.0.0 of vyos.vyos collection, we see the following error from AH.

```
Status: failed
Version: 1.0.0
Error message:
'terminated'
  File "/venv/lib64/python3.6/site-packages/rq/worker.py", line 884, in perform_job
    rv = job.perform()
  File "/venv/lib64/python3.6/site-packages/rq/job.py", line 664, in perform
    self._result = self._execute()
  File "/venv/lib64/python3.6/site-packages/rq/job.py", line 670, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/venv/lib64/python3.6/site-packages/pulp_ansible/app/tasks/collections.py", line 131, in import_collection
    artifact_file, filename=filename, logger=import_logger
  File "/venv/lib64/python3.6/site-packages/galaxy_importer/collection.py", line 53, in import_collection
    return _import_collection(file, filename, logger, cfg)
  File "/venv/lib64/python3.6/site-packages/galaxy_importer/collection.py", line 68, in _import_collection
    file=file, logger=logger).run()
  File "/venv/lib64/python3.6/site-packages/galaxy_importer/ansible_test/runners/openshift_job.py", line 77, in run
    job.cleanup()
  File "/venv/lib64/python3.6/site-packages/galaxy_importer/ansible_test/runners/openshift_job.py", line 321, in cleanup
    reason = pod['status']['containerStatuses'][0]['state']['terminated']['reason']
```

##### STEPS TO REPRODUCE

Unsure steps to reproduce, but is specific to vyos.vyos

##### ACTUAL RESULTS

```

```

**Comment by chouseknecht** [comment] 2020-06-24 22:32
We disabled `ansible-test` in order to get the collection uploaded. Will re-enable once @cutwater is back.

**Comment by chouseknecht** [comment] 2020-06-30 14:03
Duplicate of #130

**Closed** 2020-07-22 20:36 UTC
Labels: area/importer, priority/high, sprint/1, status/ready-for-QE, type/enhancement
