### ISSUE TITLE
Collection imports are failing to create Openshift jobs

### ISSUE THREAD

**Issue by ironfroggy** [ansible/galaxy_ng#122] opened 2020-04-27 19:09 UTC
##### SUMMARY
Imports on QA are frequently failing to create Openshift jobs, causing the import to fail.

##### STEPS TO REPRODUCE

Publish an artifact to qa.cloud.redhat.com

##### EXPECTED RESULTS

Successful import in the logs

##### ACTUAL RESULTS

```
2020-04-27 13:00:10,412 INFO rq.worker: 1@pulp-worker-48-9pcsh: pulp_ansible.app.tasks.collections.import_collection(artifact_pk=UUID('23e00a52-0dea-49bc-bafb-81389a41d163'), expected_name='collection_dep_a_pikmosgn', expected_namespace='autohubtest2', expected_version='1.0.0', repository_pk=UUID('339b15d5-e9be-41f5-b8ef-629fd6960968')) (64d14642-743a-454a-b041-078676e5ac77)
2020-04-27 13:00:10,455 INFO pulp_ansible.app.tasks.collections: Processing collection from artifact/d2/1ea08aa3708c97c1d760a9560addecdca644aa4c31026e5613deca80787e77
2020-04-27 13:07:19,430 INFO pulp_ansible.app.tasks.collections: Collection processing was not successfull: Could not create pod assocated with job
2020-04-27 13:07:19,544 ERROR rq.worker: galaxy_importer.exceptions.AnsibleTestError: Could not create pod assocated with job
Traceback (most recent call last):
  File "/venv/lib64/python3.6/site-packages/rq/worker.py", line 884, in perform_job
    rv = job.perform()
  File "/venv/lib64/python3.6/site-packages/rq/job.py", line 664, in perform
    self._result = self._execute()
  File "/venv/lib64/python3.6/site-packages/rq/job.py", line 670, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/venv/lib64/python3.6/site-packages/pulp_ansible/app/tasks/collections.py", line 131, in import_collection
    artifact_file, filename=filename, logger=import_logger
  File "/venv/lib64/python3.6/site-packages/galaxy_importer/collection.py", line 53, in import_collection
    return _import_collection(file, filename, logger, cfg)
  File "/venv/lib64/python3.6/site-packages/galaxy_importer/collection.py", line 68, in _import_collection
    file=file, logger=logger).run()
  File "/venv/lib64/python3.6/site-packages/galaxy_importer/ansible_test/runners/openshift_job.py", line 68, in run
    job.wait_on_pod_ready()
  File "/venv/lib64/python3.6/site-packages/galaxy_importer/ansible_test/runners/openshift_job.py", line 265, in wait_on_pod_ready
    raise exceptions.AnsibleTestError('Could not create pod assocated with job')
galaxy_importer.exceptions.AnsibleTestError: Could not create pod assocated with job
```

**Comment by ironfroggy** [comment] 2020-04-27 19:10
We have to determine if the cause of these failures is specific to the QA environment and if it endangers production AH as well.

**Comment by awcrosby** [comment] 2020-04-28 20:57
Some info found while investigating: Looking at the logs, this occurred in a 30min time period of 2020-04-27 09:07 - 09:37 on QA and did not occur on CI. This error can be caused by network timeouts.

**Comment by awcrosby** [comment] 2020-04-30 14:58
Additional imports have occurred via test runs since last check above. Kibana log check for `message:"raise exceptions.AnsibleTestError('Could not create pod assocated with job')"` shows this occurred on 3 imports on 2020-04-28 in a 14min period on QA, and has not occurred on CI.

**Comment by awcrosby** [comment] 2020-05-07 19:16
__Updated issue summary__:
With high job pod resources, it seems CI and QA encounter `Failed Scheduling` many times. Currently it takes from 4min to 6min to schedule and this intermittently hits an internally configured timeout of 5min which fails the import that uses this job.

`Failed Scheduling 0/35 nodes are available: 2 Insufficient memory, 21 Insufficient cpu, 6 node(s) didn't match node selector, 8 node(s) had taints that the pod didn't tolerate. 25 times in the last 1 minute`

An attempt to fix: remove recently added `request` structure, keep `limit` memory higher to avoid OOM `memory: 1Gi`, lower `limit` cpu to allow easier scheduling `cpu: 500m`

**Comment by awcrosby** [comment] 2020-06-16 13:44
Should be resolved by resource edits in our [OCP deployment](https://github.com/RedHatInsights/e2e-deploy/pull/1761)

**Closed** 2020-06-17 14:33 UTC
Labels: area/importer, priority/high, sprint/4, status/ready-for-QE, type/bug
